### ISSUE TITLE
11.0.0 LUA Error

### ISSUE THREAD

**Issue by Raiukage** [glassleo/Paragon#10]
From the look of this error, it looks like the new UI for Warbands has completely broken this.

10x Paragon/Core.lua:331: attempt to call global 'GetFactionInfoByID' (a nil value)
[string "@Paragon/Core.lua"]:331: in function <Paragon/Core.lua:180>
[string "@Paragon/Core.lua"]:859: in function <Paragon/Core.lua:801>

Locals:
(for state) = <table> {
 loamm niffen = <table> {
 }
 order of the awakened = <table> {
 }
 order of embers = <table> {
 }
 steamwheedle preservation society = <table> {
 }
 bloodsail buccaneers = <table> {
 }
 the undying army = <table> {
 }
 baroness vashj = <table> {
 }
 hand of the prophet = <table> {
 }
 death's advance = <table> {
 }
 argussian reach = <table> {
 }
 frenzyheart tribe = <table> {
 }
 the archivists' codex = <table> {
 }
 champions of azeroth = <table> {
 }
 the violet eye = <table> {
 }
 uldum accord = <table> {
 }
 arakkoa outcasts = <table> {
 }
 ravenholdt = <table> {
 }
 the saberstalkers = <table> {
 }
 sha'leth = <table> {
 }
 dragonscale expedition = <table> {
 }
 old hillpaw = <table> {
 }
 the wardens = <table> {
 }
 7th legion = <table> {
 }
 the klaxxi = <table> {
 }
 choofa = <table> {
 }
 the tillers = <table> {
 }
 orgrimmar = <table> {
 }
 thorium brotherhood = <table> {
 }
 fish fellreed = <table> {
 }
 gadgetzan = <table> {
 }
 alexandros mograine = <table> {
 }
 silverwing sentinels = <table> {
 }
 corbyn = <table> {
 }
 frostwolf orcs = <table> {
 }
 court of farondis = <table> {
 }
 pearlfin jinyu = <table> {
 }
 dream wardens = <table> {
 }
 the anglers = <table> {
 }
 the taunka = <table> {
 }
 tushui pandaren = <table> {
 }
 shado-pan = <table> {
 }
 impus = <table> {
 }
 lady moonberry = <table> {
 }
 the consortium = <table> {
 }
 leorajh = <table> {
 }
 maruuk centaur = <table> {
 }
 the aldor = <table> {
 }
 armies of legionfall = <table> {
 }
 conjurer margoss = <table> {
 }
 chromie = <table> {
 }
 delvar ironfist = <table> {
 }
 stormwind = <table> {
 }
 tranquillien = <table> {
 }
 tortollan seekers = <table> {
 }
 talon's vengeance = <table> {
 }
 guild = <table> {
 }
 ogri'la = <table> {
 }
 ratchet = <table> {
 }
 everlook = <table> {
 }
 booty bay = <table> {
 }
 warsong outriders = <table> {
 }
 plague deviser marileth = <table> {
 }
 winterpelt furbolg = <table> {
 }
 the defilers = <table> {
 }
 cobalt assembly = <table> {
 }
 grandmaster vole = <table> {
 }
 vol'jin's headhunters = <table> {
 }
 rendle and cudgelface = <table> {
 }
 vivianne = <table> {
 }
 the honorbound = <table> {
 }
 netherwing = <table> {
 }
 undercity = <table> {
 }
 the nightfallen = <table> {
 }
 valdrakken accord = <table> {
 }
 cryptkeeper kassir = <table> {
 }
 kleia and pelagos = <table> {
 }
 stitchmasters = <table> {
 }
 the frostborn = <table> {
 }
 thunder bluff = <table> {
 }
 silvermoon city = <table> {
 }
 kirin tor = <table> {
 }
 cenarion expedition = <table> {
 }
 the sunreavers = <table> {
 }
 huojin pandaren = <table> {
 }
 nat pagle = <table> {
 }
 order of the cloud serpent = <table> {
 }
 darkspear trolls = <table> {
 }
 bilgewater cartel = <table> {
 }
 brood of nozdormu = <table> {
 }
 the league of arathor = <table> {
 }
 stormpike guard = <table> {
 }
 obsidian warders = <table> {
 }
 the wyrmrest accord = <table> {
 }
 sha'tari skyguard = <table> {
 }
 the august celestials = <table> {
 }
 ironforge = <table> {
 }
 operation: shieldwall = <table> {
 }
 avengers of hyjal = <table> {
 }
 tormmok = <table> {
 }
 soridormi = <table> {
 }
 glimmerogg racer = <table> {
 }
 marasmius = <table> {
 }
 hydraxian waterlords = <table> {
 }
 golden lotus = <table> {
 }
 gilneas = <table> {
 }
 dreamweavers = <table> {
 }
 knights of the ebon blade = <table> {
 }
 the earthen ring = <table> {
 }
 darnassus = <table> {
 }
 thrallmar = <table> {
 }
 sabellian = <table> {
 }
 wintersaber trainers = <table> {
 }
 the avowed = <table> {
 }
 council of exarchs = <table> {
 }
 argent crusade = <table> {
 }
 argent dawn = <table> {
 }
 shado-pan assault = <table> {
 }
 cenarion circle = <table> {
 }
 the ascended = <table> {
 }
 tina mudclaw = <table> {
 }
 baradin's wardens = <table> {
 }
 highmountain tribe = <table> {
 }
 darkmoon faire = <table> {
 }
 the sha'tar = <table> {
 }
 the scryers = <table> {
 }
 shattered sun offensive = <table> {
 }
 mikanikos = <table> {
 }
 lower city = <table> {
 }
 proudmoore admiralty = <table> {
 }
 talanji's expedition = <table> {
 }
 gina mudc

**Comment by glassleo** [comment]
Seems like they have changed the reputation API quite a bit, might take a while until I get it working.

**Comment by glassleo** [comment]
It wasn't that bad, will release a working version within a few hours.

**Comment by Raiukage** [comment]
Thank you very much!
