### ISSUE TITLE
Wrong reputation level displayed

### ISSUE THREAD

**Issue by voxem** [glassleo/Paragon#6]
There seems to be a problem with reputation levels. On a character that has never met Chee Chee, nor Old Hillpaw (so no reputation, not even _Stranger_), the tooltip for _Blue Feather_ displays like this:
![blue_feather](https://user-images.githubusercontent.com/59542429/206910884-e162d3f0-350d-44bf-b867-05b7a3de3bb1.jpg)
I don't know if it's related to the other issue I opened a moment ago.

**Comment by glassleo** [comment]
Yep, this is related to #5 and I have found the bug. Will push an update to the addon soon.

Unfortunately it means you'll have to relog all your alts again after the update since the current version of Paragon stores friendship reputation levels incorrectly.

**Comment by glassleo** [comment]
Fixed in [Chalcedony 5](https://github.com/glassleo/Paragon/releases/)
